#!/bin/bash
# leaderboard daemon
# description: leaderboard daemon
# processname: leaderboard

DAEMON_PATH="/home/localadmin/LeaderboardREST"

DAEMON=java 
DAEMONOPTS="-cp commons-codec-1.9.jar:jetty-io-9.0.2.v20130417.jar:jetty-security-9.0.2.v20130417.jar:log4j-1.2.14.jar:jetty-http-9.0.2.v20130417.jar:jetty-servlet-9.0.2.v20130417.jar:jetty-xml-9.0.2.v20130417.jar:jetty-webapp-9.0.2.v20130417.jar:slf4j-log4j12-1.6.1.jar:mysql-connector-java-5.1.25-bin.jar:slf4j-api-1.6.1.jar:jetty-util-9.0.2.v20130417.jar:javax.servlet-3.0.0.v201112011016.jar:spark-core-1.1.1.jar:com.eclipsesource.json_2013-10-22.jar:jetty-server-9.0.2.v20130417.jar:slf4j-api-1.7.2.jar:mysql-connector-java-5.1.25-bin.jar:gson-2.2.4.jar:com.eclipsesource.json_2013-10-22.jar:. LeaderboardREST"

NAME=leaderboard
DESC="leaderboard rest server"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
